// Industry starter templates. Each pre-fills the plan form so a user can start from a
// realistic example rather than a blank page. Tagged to the current year and refreshed
// annually (see templateYear / refreshedFor below).

export const templateYear = () => new Date().getFullYear();

// Field shape matches the generator form: { org, industry, stage, goals, objectives, horizon, constraints }
// Plus: docType (strategic | business), category (for grouping), emoji (card icon).
export const TEMPLATES = [
  {
    id: "cafe", emoji: "☕", name: "Café / coffee shop", category: "Hospitality & food",
    docType: "business", org: "Sample Café Co.", industry: "Café & coffee",
    stage: "Startup", horizon: "3 years",
    goals: "Open a profitable neighbourhood café, build a loyal regular customer base, and reach break-even within the first year.",
    objectives: "Serve 150+ customers a day within 12 months; keep food-cost under 32% of sales; achieve a 4.5+ star average review score.",
    constraints: "Tight fit-out budget, competition from nearby chains, hiring reliable baristas.",
  },
  {
    id: "restaurant", emoji: "🍽️", name: "Restaurant", category: "Hospitality & food",
    docType: "business", org: "Sample Restaurant", industry: "Restaurant & dining",
    stage: "Startup", horizon: "3 years",
    goals: "Launch a mid-range dine-in restaurant, establish a strong local reputation, and expand to a second sitting/venue over three years.",
    objectives: "Fill 70%+ of covers on weekends; keep labour under 30% of revenue; build a bookings database of 2,000 diners.",
    constraints: "High upfront kitchen costs, seasonal demand, staff turnover.",
  },
  {
    id: "salon", emoji: "💇", name: "Hair & beauty salon", category: "Personal services",
    docType: "business", org: "Sample Salon", industry: "Hair & beauty",
    stage: "Startup", horizon: "3 years",
    goals: "Open a boutique salon, build a booked-out stylist team, and grow recurring rebooking revenue.",
    objectives: "Reach 65% chair-utilisation; 50%+ of clients rebooking; introduce a retail product line for 15% of revenue.",
    constraints: "Attracting and retaining skilled stylists, fit-out cost, local competition.",
  },
  {
    id: "gym", emoji: "🏋️", name: "Gym / fitness studio", category: "Personal services",
    docType: "business", org: "Sample Fitness", industry: "Fitness & wellness",
    stage: "Startup", horizon: "3 years",
    goals: "Launch a membership-based fitness studio and build predictable recurring revenue with high retention.",
    objectives: "Reach 400 active members; keep monthly churn under 4%; add small-group PT for 25% of revenue.",
    constraints: "Equipment finance, seasonal sign-up cycles, member retention.",
  },
  {
    id: "saas", emoji: "💻", name: "SaaS startup", category: "Technology",
    docType: "business", org: "Sample SaaS", industry: "Software (SaaS)",
    stage: "Idea / pre-launch", horizon: "3 years",
    goals: "Launch a B2B SaaS product, reach product-market fit, and grow to sustainable monthly recurring revenue.",
    objectives: "Reach $50k MRR; keep net revenue retention above 100%; get CAC payback under 12 months.",
    constraints: "Limited runway, engineering capacity, crowded market, long sales cycles.",
  },
  {
    id: "ecommerce", emoji: "🛒", name: "E-commerce store", category: "Retail",
    docType: "business", org: "Sample Online Store", industry: "E-commerce & retail",
    stage: "Startup", horizon: "3 years",
    goals: "Grow an online store into a recognised brand with repeat customers and healthy contribution margins.",
    objectives: "Reach $1M annual revenue; 30%+ repeat-purchase rate; blended ROAS above 3.0.",
    constraints: "Ad-cost inflation, inventory cash-flow, shipping and returns.",
  },
  {
    id: "trucking", emoji: "🚚", name: "Trucking / freight", category: "Logistics & trades",
    docType: "business", org: "Sample Freight Co.", industry: "Transport & logistics",
    stage: "Growth", horizon: "5 years",
    goals: "Expand a freight and logistics operation with more contracts, a larger fleet, and improved on-time performance.",
    objectives: "Grow to 20 vehicles; 98%+ on-time delivery; keep fuel and maintenance under target cost-per-km.",
    constraints: "Fuel price volatility, driver shortages, vehicle finance and compliance.",
  },
  {
    id: "construction", emoji: "🏗️", name: "Construction / builder", category: "Logistics & trades",
    docType: "strategic", org: "Sample Construction", industry: "Construction & building",
    stage: "Established / mature", horizon: "5 years",
    goals: "Win larger commercial contracts, adopt technology in operations, and grow margins steadily while managing risk.",
    objectives: "Grow revenue 15% a year; improve project gross margin by 4 points; reduce rework and safety incidents.",
    constraints: "Materials cost swings, skilled-labour shortages, project timeline and permit delays.",
  },
  {
    id: "trades", emoji: "🔧", name: "Plumbing / electrical trade", category: "Logistics & trades",
    docType: "business", org: "Sample Trades Co.", industry: "Trades & home services",
    stage: "Startup", horizon: "3 years",
    goals: "Build a reliable trades business with recurring maintenance contracts and a small team of qualified tradespeople.",
    objectives: "Book 80% of capacity; win 15 recurring maintenance contracts; keep callback rate under 3%.",
    constraints: "Hiring licensed tradespeople, cash-flow on jobs, seasonal demand.",
  },
  {
    id: "landscaping", emoji: "🌿", name: "Landscaping / gardening", category: "Logistics & trades",
    docType: "business", org: "Sample Landscaping", industry: "Landscaping & grounds",
    stage: "Startup", horizon: "3 years",
    goals: "Grow a landscaping business with recurring maintenance clients alongside larger design-and-build projects.",
    objectives: "Sign 40 recurring maintenance clients; win 6 design-build projects a year; keep crews 80% utilised.",
    constraints: "Weather seasonality, equipment finance, labour availability.",
  },
  {
    id: "cleaning", emoji: "🧹", name: "Cleaning services", category: "Personal services",
    docType: "business", org: "Sample Cleaning Co.", industry: "Commercial & domestic cleaning",
    stage: "Startup", horizon: "3 years",
    goals: "Build a cleaning business with stable recurring commercial contracts and a dependable casual workforce.",
    objectives: "Secure 25 recurring commercial contracts; keep staff turnover under 20%; 95%+ client retention.",
    constraints: "Staff reliability, thin margins, winning contracts from incumbents.",
  },
  {
    id: "childcare", emoji: "🧸", name: "Childcare / early learning", category: "Care & education",
    docType: "strategic", org: "Sample Early Learning", industry: "Childcare & early education",
    stage: "Established / mature", horizon: "5 years",
    goals: "Maintain high-quality care, achieve full enrolment, and meet all regulatory and accreditation standards.",
    objectives: "Reach 95% occupancy; retain qualified educators; exceed accreditation benchmarks.",
    constraints: "Strict ratios and regulation, educator shortages, funding changes.",
  },
  {
    id: "clinic", emoji: "🩺", name: "Medical / dental clinic", category: "Care & education",
    docType: "strategic", org: "Sample Clinic", industry: "Healthcare & allied health",
    stage: "Established / mature", horizon: "5 years",
    goals: "Grow patient numbers, add practitioners and services, and improve patient experience while maintaining compliance.",
    objectives: "Add 3 practitioners; reduce wait times; grow recurring/recall appointments by 25%.",
    constraints: "Practitioner recruitment, regulatory compliance, equipment investment.",
  },
  {
    id: "realestate", emoji: "🏠", name: "Real estate agency", category: "Professional services",
    docType: "strategic", org: "Sample Realty", industry: "Real estate",
    stage: "Growth", horizon: "5 years",
    goals: "Grow market share in the local area, build a strong rent-roll for recurring income, and strengthen the brand.",
    objectives: "Grow the rent-roll to 400 properties; win 12% listing market share; improve days-on-market.",
    constraints: "Market cycles, agent recruitment and retention, portal/advertising costs.",
  },
  {
    id: "accounting", emoji: "📊", name: "Accounting / bookkeeping", category: "Professional services",
    docType: "strategic", org: "Sample Accounting", industry: "Accounting & bookkeeping",
    stage: "Established / mature", horizon: "5 years",
    goals: "Shift toward recurring advisory work, adopt automation, and grow a loyal small-business client base.",
    objectives: "Move 60% of revenue to recurring; automate compliance workflows; grow clients 15% a year.",
    constraints: "Talent shortages, pricing pressure, technology change.",
  },
  {
    id: "agency", emoji: "📣", name: "Marketing agency", category: "Professional services",
    docType: "business", org: "Sample Agency", industry: "Marketing & creative services",
    stage: "Startup", horizon: "3 years",
    goals: "Build a marketing agency with retained clients, a repeatable delivery model, and a strong portfolio.",
    objectives: "Reach 15 retainer clients; 90%+ retainer retention; keep utilisation above 75%.",
    constraints: "Client concentration risk, talent costs, feast-or-famine pipeline.",
  },
  {
    id: "itservices", emoji: "🖥️", name: "IT / managed services", category: "Technology",
    docType: "business", org: "Sample IT Services", industry: "IT & managed services",
    stage: "Growth", horizon: "5 years",
    goals: "Grow a managed-services provider with recurring monthly contracts and strong service-level performance.",
    objectives: "Reach $2M recurring revenue; 97%+ SLA attainment; keep churn under 5%.",
    constraints: "Technician recruitment, cybersecurity risk, margin pressure.",
  },
  {
    id: "farming", emoji: "🌾", name: "Farming / agriculture", category: "Primary industry",
    docType: "strategic", org: "Sample Farm", industry: "Agriculture & primary production",
    stage: "Established / mature", horizon: "10 years",
    goals: "Improve yield and sustainability, diversify income streams, and build resilience to seasonal and market risk.",
    objectives: "Lift yield per hectare; add a value-added product line; reduce input costs and water use.",
    constraints: "Weather and climate risk, commodity price swings, capital-intensive equipment.",
  },
  {
    id: "tourism", emoji: "🧳", name: "Tourism / accommodation", category: "Hospitality & food",
    docType: "business", org: "Sample Tourism Co.", industry: "Tourism & accommodation",
    stage: "Startup", horizon: "3 years",
    goals: "Build a tourism/accommodation business with strong occupancy, great reviews, and reduced seasonality.",
    objectives: "Reach 70% annual occupancy; 4.6+ review average; grow direct (non-OTA) bookings to 40%.",
    constraints: "Seasonality, online-travel-agent commissions, marketing reach.",
  },
  {
    id: "nonprofit", emoji: "🤝", name: "Non-profit / charity", category: "Care & education",
    docType: "strategic", org: "Sample Non-Profit", industry: "Non-profit & community",
    stage: "Growth", horizon: "5 years",
    goals: "Grow the organisation's impact and reach, diversify funding, and strengthen governance and volunteer capacity.",
    objectives: "Grow served beneficiaries by 40%; diversify to 4 funding sources; build a stable volunteer base.",
    constraints: "Grant dependence, volunteer retention, reporting and compliance load.",
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(TEMPLATES.map((t) => t.category))];
